# Setup
title:            Thirsty Tuna
url:              https://vinayreddy.github.io
baseurl:          '/'
# paginate:         5

# About and contact
author:
  name:           'Vinay Reddy'
  email:          vinayvinay@gmail.com

# Gems
plugins:
  - jekyll-gist

# Custom vars
version:          0.0.1
